from typing import Protocol, runtime_checkable

from domain.entities.cuenta import Cliente, Cuenta, Movimiento


@runtime_checkable
class ICuentaRepository(Protocol):
    def get_cliente(self, cliente_id: str) -> Cliente | None: ...
    def get_cuenta(self, cuenta_id: str) -> Cuenta | None: ...
    def get_movimientos(self, cuenta_id: str, limit: int) -> list[Movimiento]: ...
    def crear_cuenta(self, cliente_id: str, tipo: str, moneda: str) -> Cuenta: ...
