from typing import Protocol, runtime_checkable

from domain.entities.transferencia import LimiteTransferencia, Transferencia


@runtime_checkable
class ITransferenciaRepository(Protocol):
    def get_by_id(self, transfer_id: str) -> Transferencia | None: ...
    def get_by_cuenta(self, cuenta_id: str) -> list[Transferencia]: ...
    def get_limites(self, cliente_id: str) -> LimiteTransferencia | None: ...
    def crear(self, origen: str, destino: str, monto: float, descripcion: str) -> Transferencia: ...
